[rust]
rpath = false
channel = "stable"

[build]
build = "x86_64-unknown-linux-gnu"
target = ["x86_64-unknown-linux-gnu", "armv4t-unknown-linux-uclibceabi"]

docs = false
extended = true
tools = ["cargo"]

install-stage = 1

[target.armv4t-unknown-linux-uclibceabi]
cc = "arm-unknown-linux-uclibcgnueabi-gcc"
cxx = "arm-unknown-linux-uclibcgnueabi-g++"
ar = "arm-unknown-linux-uclibcgnueabi-ar"
ranlib = "arm-unknown-linux-uclibcgnueabi-ranlib"
linker = "arm-unknown-linux-uclibcgnueabi-gcc"
